version: 2
jobs:
  test-all:
    docker:
      - image: sudachen/go1137-ci

    parallelism: 1

    environment:
      MXNET_ENFORCE_DETERMINISM: 1
      OMP_NUM_THREADS: 4
      MXNET_OMP_MAX_THREADS: 4
      CC_TEST_REPORTER_ID: 0adaf2b827ad86d0b0025eb4bd0e78bd47774e7671ac9613e533e9e3762067ce

    steps:
      - checkout

      - restore_cache:
          # https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: make build

      - run: make run-tests

      - run: /usr/local/bin/cc-test-reporter after-build -t gocov

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-all